### ISSUE TITLE
Race condition in _handle

### ISSUE THREAD

**Issue by isra17** [Flared/dramatiq-abort#1]
```
RuntimeError: dictionary changed size during iteration
<listcomp> (/opt/venv/lib/python3.7/site-packages/dramatiq_abort/middleware.py:113)
```

**Comment by theSage21** [comment]
@isra17 Is there a known patch for this? We're facing the same thing at work.

If not I can take a stab at trying to fix this.

**Comment by isra17** [comment]
Forgot about a commit a friend made but didn't create a PR for! Fixed now :D
