### ISSUE TITLE
Is it possible to get all messages directrly from the broker rather than storing them?

### ISSUE THREAD

**Issue by iwishiwasaneagle** [Flared/dramatiq-abort#14]
So for example, I run 1 million jobs my PC crashes but the server is still running the jobs. How do I get the `message_id` to cancel the jobs? From what I can see, the `message_id` is not linked to the Redis key or am I wrong there?

**Comment by isra17** [comment]
If you want to cancel all the running task you should just kill the worker. Looking at your proposed solution it doesn't fix the 1 millions jobs issue. You need to wipe the jobs queue, as killing a few thread is only going to cancel a few task before the workers pick up the next millions of enqueued job.

**Comment by iwishiwasaneagle** [comment]
Okay, maybe my example wasn't the best. What if you had 1000 very long running tasks? I just feel like being able to cancel a task without knowing teh message_id's would be beneficial. The queue can be flushed by other means as well.

**Comment by isra17** [comment]
The point still stand. If you have 1000 very long running tasks you probably need to stop the worker, flush the queue, then restart the worker. I don't think adding a way to kill all running tasks in a worker would have much benefits over killing the worker.

**Comment by iwishiwasaneagle** [comment]
Well let's consider you're running the task on a remote machine. It'd be more convenient to write a script to flush the queue, and kill all running tasks than to ssh in, and kill the machine and also write a script to flush the queue.

**Comment by isra17** [comment]
Sorry, I still don't see it as a useful enough feature to add it.
