### ISSUE TITLE
Aborting a worker that runs a subprocess

### ISSUE THREAD

**Issue by aranvir** [Flared/dramatiq-abort#22]
Hi, I recently got started with dramatiq and was now looking for a way to abort workers.

My workers are usually just wrappers for `subprocess.run` or `subprocess.Popen` with some custom timeout handling. I realized that the abort signaling does not work for these workers. 

In the description for the middleware it says:

>     Note: This works by setting an async exception in the worker thread
>     that runs the actor.  This means that the exception will only get
>     called the next time that thread acquires the GIL. Concretely,
>     this means that this middleware can't cancel system calls.

So to double check that I understand it correctly: "can't cancel system calls" means that it cannot cancels thinks like `subprocess.run` as described above?
Thanks!

**Comment by isra17** [comment]
That's right. Actually you probably have a `process.wait()` somewhere in your code. One easy way to deal with it would be to set a timeout on `wait`, and check if either a timeout or cancellation happened. ie.

```python
ret = None
try:
  while ret is None:
    try:
      ret = process.wait(timeout=1)
    except subprocess.TimeoutExpired)
      pass
except Abort:
  process.signal(SIGINT)
  process.wait()
```

**Comment by aranvir** [comment]
Yea what I have is the following to deal with the timeouts in a more custom manner (I want that the log of the cancelled process reflects what happened).

So not sure if your suggestion works with `process.communicate()` as well since this will only return after the timeout or when the process concludes, right?

```python
def timeout_callback(p: subprocess.Popen, status: Dict):
    if p.poll() is None:
        os.kill(p.pid, signal.SIGINT)
        status.update({"msg": "Process killed due to timeout".encode("UTF-8")})


def run_subprocess(*args, timeout: float = 0, **kwargs):
    """Runs a subprocess with timeout where the timeout does not remove the subprocess content"""
    with subprocess.Popen(*args, **kwargs) as process:
        if timeout > 0:
            status = {}
            t = threading.Timer(timeout, timeout_callback, [process, status])
            t.start()
        stdout, stderr = process.communicate()
        if timeout > 0:
            if len(status) > 0:
                stderr += status["msg"]
                t.join()
            else:
                t.cancel()
        completed_process = subprocess.CompletedProcess(
            args=args,
            returncode=process.returncode,
            stderr=stderr,
            stdout=stdout
        )
    return completed_process
```

**Comment by aranvir** [comment]
Oh, but communicate is a wrapper for wait! I'm gonna try this, thanks!

**Comment by aranvir** [comment]
Works, thanks! I think it would make sense to add your snippet to the documentation just as an example

**Comment by isra17** [comment]
Feel free to contribute with a doc example!
